name: Test Backend
on:
  push:
    paths:
      - backend/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm ci
        working-directory: ./backend
      - run: npm test
        working-directory: ./backend
