name: Test E2E
on:
  push:
    paths:
      - frontend/**
      - backend/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Run the setup script
        run: |
          sh ./e2e/scripts/setup.sh
      - name: Start Services & Run E2E testing
        run: |
          sh ./e2e/scripts/runServe.sh &
          sh ./e2e/scripts/runExpress.sh &
          sh ./e2e/scripts/runTests.sh
